- name: configure mysql server
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1 
  tasks:
    - name: Install my sql server
      ansible.builtin.package:
        name: mysql-server
        state: installed

    - name: Start and enable mysql server
      ansible.builtin.debug:
        name: mysqld
        state: started
        enable: yes

    - name: connect to mysql server
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_host: mysql.jiocoinmarket.online
      register: mysql_info
    
    - name: print output
      ansible.builtin.debug:
        mysql: "Mysql info: {{ mysql_info }}"

    - name: set root password
      ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"